import { Card, CardContent, CardFooter, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Suspense } from "react";
import { DropzoneClient } from "./_dropzoneClient";
import { getCurrentUser } from "@/services/clerk/lib/getCurrentAuth";
import { notFound } from "next/navigation";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { cacheTag } from "next/dist/server/use-cache/cache-tag";
import { getUserResumeIdTag } from "@/features/users/db/cache/userResume";
import { db } from "@/drizzle/db";
import { eq } from "drizzle-orm";
import { userResumeTable } from "@/drizzle/schema";
import { MarkdownRenderer } from "@/components/markdown/MarkdownRenderer";

export default function UserResumePage() {
    return <div className="max-w-4xl mx-auto py-8 space-y-6 px-4">
        <h1 className="text-2xl font-bold">Upload Your Resume</h1>
        <Card>
            <CardContent>
                <DropzoneClient />
            </CardContent>
            <Suspense>
                <ResumeDetails />
            </Suspense>
        </Card>
        <Suspense>
            <AISummaryCard />
        </Suspense>
    </div>
}

async function ResumeDetails() {
    const { userId } = await getCurrentUser()
    if (!userId) return notFound()

    const userResume = await getUserResume(userId)
    if (!userResume) return null


    return <CardFooter>
        <Button asChild>
            <Link href={userResume.resumeFileUrl} target="_blank" rel="noopener noreferrer">
                View Resume
            </Link>
        </Button>
    </CardFooter>
}

async function AISummaryCard() {
    const { userId } = await getCurrentUser()
    if (!userId) return notFound()

    const userResume = await getUserResume(userId)
    if (!userResume || userResume.aiSummary == null) return null

    console.log("AI Summary:", userResume.aiSummary)
    return <Card>
        <CardHeader className="border-b">
            <CardTitle>AI Summary</CardTitle>
            <CardDescription>
                This summary is generated by AI based on the resume you uploaded. It extracts key skills, experience, and qualifications to give you a quick overview of your resume's content.
            </CardDescription>
        </CardHeader>
        <CardContent>
            <MarkdownRenderer source={userResume.aiSummary} />
        </CardContent>
    </Card>
}

async function getUserResume(userId: string) {
    "use cache"
    cacheTag(getUserResumeIdTag(userId))

    return await db.query.userResumeTable.findFirst({
        where: eq(userResumeTable.userId, userId)
    })
}