import type { Metadata } from "next";
import { IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import "./globals.css";
import "@mdxeditor/editor/style.css";
import { ClerkProvider } from "@/services/clerk/components/Provider";
import { Toaster } from "@/components/ui/sonner";
import { UploadThingSSR } from "@/services/uploadthing/components/UploadThingSSR";

const ibmPlexSans = IBM_Plex_Sans({
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"],
});

const ibmPlexMono = IBM_Plex_Mono({
  weight: ["400", "500", "700"],
  style: "normal",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "AXIS",
  description: "Generated by Kio!",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${ibmPlexSans.variable} ${ibmPlexMono} font-sans`}>
          <UploadThingSSR />
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
